# Generated by Django 4.1.4 on 2022-12-14 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_user', models.CharField(editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.CharField(blank=True, max_length=100, null=True)),
                ('product_status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], max_length=50)),
                ('product_prize', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/product_images')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
