# Generated by Django 4.1.4 on 2022-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Vegetables', 'Vegetables'), ('Furniture', 'Furniture'), ('Medicines', 'Medicines')], default='Clothing', max_length=50),
            preserve_default=False,
        ),
    ]
