# Generated by Django 4.1.4 on 2022-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_prize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
